### ISSUE TITLE
希望增加更多城市的疫情地图

### ISSUE THREAD

**Issue by LTDSA** [xingrz/cdata-gd#4]
佛山市可供参考的数据源：[http://wjj.foshan.gov.cn/zwgk/ztzl/xxgzbdgrdfyyqfk/](http://wjj.foshan.gov.cn/zwgk/ztzl/xxgzbdgrdfyyqfk/)（佛山市卫生健康局）

**Comment by LTDSA** [comment]
> 佛山市可供参考的数据源：http://wjj.foshan.gov.cn/zwgk/ztzl/xxgzbdgrdfyyqfk/（佛山市卫生健康局）

F12 抓出来的 JSON API：[http://wjj.foshan.gov.cn/postmeta/i/34374.json](http://wjj.foshan.gov.cn/postmeta/i/34374.json)

**Comment by xingrz** [comment]
12月开始佛山只公布社会面了，这个问题暂时关闭。
