### ISSUE TITLE
分城市查看数据无法正常显示

### ISSUE THREAD

**Issue by Laplacence** [xingrz/cdata-gd#7]
rt

**Comment by xingrz** [comment]
请附上截图。

**Comment by Laplacence** [comment]
![Snipaste_2022-12-04_14-40-14](https://user-images.githubusercontent.com/22720300/205478095-a072a793-318a-41ae-837b-419303707d65.png)
![Snipaste_2022-12-04_14-40-06](https://user-images.githubusercontent.com/22720300/205478099-30280bab-f544-4f05-9422-4ac9e4c0ab13.png)

100%复现 

Chrome Version 108.0.5359.95 (Official Build) (64-bit)
Android Chrome Version 107.0.5304.141

**Comment by xingrz** [comment]
感谢。已修复。
